### ISSUE TITLE
Genetic evolution wont loop

### ISSUE THREAD

**Issue by gucio1200** [Gab0/gekkoJaponicus#16]
EPOCH 599/600
Average profit 3.889%   Deviation 3.148
Maximum profit 9.149%   Minimum profit -1.130%

Traceback (most recent call last):
  File "japonicus.py", line 63, in <module>
    gekko_generations(strat, GenerationMethod)
  File "/opt/neural/evolution_generations.py", line 144, in gekko_generations
    FinalIndividueSettings = reconstructTradeSettings(FinalIndividue)
NameError: name 'reconstructTradeSettings' is not defined

**Comment by Gab0** [comment]
fixed, thanks for the report ^^
