### ISSUE TITLE
CSV file not created at start

### ISSUE THREAD

**Issue by gucio1200** [Gab0/gekkoJaponicus#17]
Traceback (most recent call last):
  File "japonicus.py", line 63, in <module>
    gekko_generations(strat, GenerationMethod)
  File "/opt/neural/evolution_generations.py", line 125, in gekko_generations
    write_evolution_logs(W, Stats)
  File "/opt/neural/coreFunctions.py", line 112, in write_evolution_logs
    os.remove(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'output/evolution_gen.csv'

**Comment by Gab0** [comment]
Fixed, thanks for the report ^^
btw some heavy stuff has been modified with this fix. So more strange stuff might happen. (I tested x])

**Comment by gucio1200** [comment]
Im testing on the spot with fast docker images.
And no worry, i will report any if they will appear :)
