### ISSUE TITLE
Updating the watch market

### ISSUE THREAD

**Issue by harssh** [Gab0/gekkoJaponicus#20]
Can you provide some details on how to update the market like exchange , asset and currency ?
I tried updating Settings.py and example-config.js but it still hots USDT and BTC

**Comment by Gab0** [comment]
Those settings are now under generations.dataset_source on Settings.py. Can you confirm the usability? x]

**Comment by harssh** [comment]
Sure will try to run script tonight after updates ...

**Comment by harssh** [comment]
It's throwing 

`WEBSERVER MODE
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "japonicus.py", line 65, in <module>
    gekko_generations(strat, GenerationMethod)
  File "/Users/harssh/Documents/gekko/gekkoJaponicus-dtaset/evolution_generations.py", line 34, in gekko_generations
    GenerationMethod = promoterz.selectRepresentationMethod(GenerationMethod)
  File "/Users/harssh/Documents/gekko/gekkoJaponicus-dtaset/promoterz/base.py", line 11, in selectRepresentationMethod
    M = importlib.import_module("promoterz.representation.%s" % methodname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'promoterz.representation.standard'**
^CException ignored in: <module 'threading' from '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
`

**Comment by Gab0** [comment]
This error has been solved on the recent rework. 
Enjoy this new batch of bugs xD
(jk, I'm trying to do a better quality control)
