### ISSUE TITLE
ValueError: empty range for randrange()

### ISSUE THREAD

**Issue by jwijmans** [Gab0/gekkoJaponicus#24]
Hi,

I've tried long but I can't get the script running. I am now getting below error. Could you help me further with this? Thanks in advance!

pi@raspi:~/gekkoJaponicus $ python3 japonicus.py -g
Traceback (most recent call last):
  File "japonicus.py", line 66, in <module>
    gekko_generations(settings_, GenerationMethod)
  File "/home/pi/gekkoJaponicus/evolution_generations.py", line 34, in gekko_generations
    World = promoterz.world.World(GlobalTools, loops, genconf, TargetParameters, NB_LOCALE, EnvironmentParameters=availableDataRange)
  File "/home/pi/gekkoJaponicus/promoterz/world.py", line 24, in __init__
    self.generateLocale()
  File "/home/pi/gekkoJaponicus/promoterz/world.py", line 34, in generateLocale
    L = promoterz.locale.Locale(self, name, position, random.choice(self.loops))
  File "/home/pi/gekkoJaponicus/promoterz/locale.py", line 38, in __init__
    World.EnvironmentParameters, World.genconf.deltaDays)
  File "/home/pi/gekkoJaponicus/promoterz/evaluation/gekko.py", line 259, in getRandomDateRange
    Starting= random.randint(FLms,TLms-deltams-testms)
  File "/usr/lib/python3.5/random.py", line 227, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.5/random.py", line 205, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1500662280,1500657061, -5219)

**Comment by Gab0** [comment]
Hey @jwijmans, it seems you got no available candlestick dataset available for backtesting, or timespan of your CS sets is too narrow... 
If this is true, run `$node gekko --import` to get your gekko loaded.
If not, let me know
Thanks.
