### ISSUE TITLE
ImportError: cannot import name 'functions'

### ISSUE THREAD

**Issue by rdetwiler** [Gab0/gekkoJaponicus#25]
Geting the following error when running the most recent release

`[root@cpaneldev gekkoJaponicus]# python3.6 japonicus.py -g
Traceback (most recent call last):
  File "japonicus.py", line 9, in <module>
    from evolution_generations import gekko_generations
  File "/home/btctrader/gekkoJaponicus/evolution_generations.py", line 4, in <module>
    import promoterz
  File "/home/btctrader/gekkoJaponicus/promoterz/__init__.py", line 3, in <module>
    from . import functions
ImportError: cannot import name 'functions'
`

**Comment by Gab0** [comment]
Sorry, should work now x}

**Comment by rdetwiler** [comment]
@Gab0 Thanks!!!! One more error, you may want to put some logic in for those not wanting to use AWS:

```
[root@cpaneldev gekkoJaponicus]# python3.6 japonicus.py -g
Traceback (most recent call last):
  File "japonicus.py", line 66, in <module>
    gekko_generations(settings_, GenerationMethod)
  File "/home/btctrader/gekkoJaponicus/evolution_generations.py", line 28, in gekko_generations
    RemoteHosts = promoterz.evaluation.gekko.loadHostsFile(globalconf.RemoteAWS)
  File "/home/btctrader/gekkoJaponicus/promoterz/evaluation/gekko.py", line 80, in loadHostsFile
    H = open(HostsFilePath).read().split('\n')
FileNotFoundError: [Errno 2] No such file or directory: '../AmazonSetup/hosts'

```

**Comment by Gab0** [comment]
Those bizarre bugs... thanks man

**Comment by rdetwiler** [comment]
You're welcome! Thanks for putting this awesome  I've found a few more oddities, but i'll hold off on posting them as I think they may be related to these two issues i've opened.

As a work around, I created the /AmazonSetup/hosts below the git clone dir, and put in localhost as the remote server to connect to.
