### ISSUE TITLE
TypeError: '>' not supported between instances of 'tuple' and 'int'

### ISSUE THREAD

**Issue by rdetwiler** [Gab0/gekkoJaponicus#26]
Hello,
Getting the following TypeError:

`[root@cpaneldev gekkoJaponicus]# python3.6 japonicus.py -g
Connected Remote Hosts:
http://127.0.0.1:3000
Evolving DEMA strategy;

evaluated parameters ranges:
short                         (1, 10)
long                          (20, 50)
thresholds.down               (-0.5, 0.1)
thresholds.up                 (-0.1, 0.5)
using candlestick dataset 2016-12-31 00:01:00 to 2017-10-30 00:00:00
-- Initializing Locale1
-- Initializing Locale2
        ======  EPOCH 0/500  ======
Locale1
Traceback (most recent call last):
  File "japonicus.py", line 66, in <module>
    gekko_generations(settings_, GenerationMethod)
  File "/home/btctrader/gekkoJaponicus/evolution_generations.py", line 62, in gekko_generations
    World.runEPOCH()
  File "/home/btctrader/gekkoJaponicus/promoterz/sequence/parallel_world.py", line 12, in world_EPOCH
    LOCALE.run()
  File "/home/btctrader/gekkoJaponicus/promoterz/locale.py", line 87, in run
    self.loop(self.World, self)
  File "/home/btctrader/gekkoJaponicus/promoterz/sequence/standard_loop.py", line 15, in standard_loop
    locale.population)
  File "/home/btctrader/gekkoJaponicus/promoterz/validation.py", line 32, in validatePopulation
    elif not (checkPhenotypeAttributeRanges(TargetParameters, phenotype)):
  File "/home/btctrader/gekkoJaponicus/promoterz/validation.py", line 20, in checkPhenotypeAttributeRanges
    higher = cmp[1][K] > cmp[0][K][1]
TypeError: '>' not supported between instances of 'tuple' and 'int'
`

**Comment by Gab0** [comment]
I only use -gc mode, so these bugs on other modes passes x]
working on it... thanks for the report
