### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Nophi** [Gab0/gekkoJaponicus#31]
Hi,
When I launch a test with MACD ` python3 japonicus.py -gc --strat MACD` 
I have this error : [https://pastebin.com/DHAJkWvQ](https://pastebin.com/DHAJkWvQ) (Complete error)

> Traceback (most recent call last):
  File "japonicus.py", line 93, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode)
  File "/root/gekkoJaponicus/evolution_generations.py", line 103, in gekko_gener
    World.runEPOCH()
  File "/root/gekkoJaponicus/promoterz/sequence/parallel_world.py", line 12, in
    LOCALE.run()
  File "/root/gekkoJaponicus/promoterz/locale.py", line 51, in run
    self.loop(self.World, self)
  File "/root/gekkoJaponicus/promoterz/sequence/standard_loop.py", line 73, in s
    assert(len(locale.population))
AssertionError

It works fine with the RSI strategy.
I do not know where it can come from.

Thanks

**Comment by Gab0** [comment]
Thats is some kind of a bug... this GA removes each ind below -15 profit score before offspring is generated. As no individue was above that threshold, each one was deleted and zero ind error got raised. Thats actually good on this situation. The program is gently telling you that MACD strat is crap ^^
