### ISSUE TITLE
Evaluation crashes after ~90 epochs

### ISSUE THREAD

**Issue by greenbigfrog** [Gab0/gekkoJaponicus#34]
`$ python japonicus.py -g --strat CCI -w` works for around 90/500 epochs, and then crashes:
```
Traceback (most recent call last):
  File "japonicus.py", line 89, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode, web=APP)
  File "/home/frog/gekkoJaponicus/evolution_generations.py", line 103, in gekko_generations
    World.runEPOCH()
  File "/home/frog/gekkoJaponicus/promoterz/sequence/parallel_world.py", line 31, in world_EPOCH
    World.explodeLocale(random.choice(World.locales))
  File "/home/frog/gekkoJaponicus/promoterz/world.py", line 54, in explodeLocale
    for g in range(len(web.GraphicList)):
NameError: name 'web' is not defined
```

**Comment by Gab0** [comment]
Thanks, bug confirmed & fixed
