### ISSUE TITLE
An attempt has been made to start a new process before the current process has finished

### ISSUE THREAD

**Issue by anakaine** [Gab0/gekkoJaponicus#40]
Hi, 

Attempting to run via `python japonicus.py -g --repeat 10 -i -w` and returning an error as below. I'm not sure where to begin troubleshooting this one. I'd use a custom strategy to test against, but I have none defined and the stock ones are pretty hit and miss when using gekkoGA, figured they would be with gekkoJaponicus too. 

Python 3.6.1
latest numpy (pip install numpy --upgrade)
 
```
using candlestick dataset 2017-06-10 09:03:00 to 2017-12-10 07:42:00

        ======  EPOCH 0/400  ======
Locale1
first unevaluated: 30
0 individues removed due to equality
[30]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Win10EntVM\Downloads\gekko-stable\gekko-stable\gekkoJaponicus\japonicus.py", line 99, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode, web=APP)
  File "C:\Users\Win10EntVM\Downloads\gekko-stable\gekko-stable\gekkoJaponicus\evolution_generations.py", line 103, in gekko_generations
    World.runEPOCH()
  File "C:\Users\Win10EntVM\Downloads\gekko-stable\gekko-stable\gekkoJaponicus\promoterz\sequence\parallel_world.py", line 12, in world_EPOCH
    LOCALE.run()
  File "C:\Users\Win10EntVM\Downloads\gekko-stable\gekko-stable\gekkoJaponicus\promoterz\locale.py", line 51, in run
    self.loop(self.World, self)
  File "C:\Users\Win10EntVM\Downloads\gekko-stable\gekko-stable\gekkoJaponicus\promoterz\sequence\standard_loop.py", line 33, in standard_loop
    locale.extraStats['nb_evaluated'], locale.extraStats['avgTrades'] = World.parallel.evaluatePopulation(locale)
  File "C:\Users\Win10EntVM\Downloads\gekko-stable\gekko-stable\gekkoJaponicus\promoterz\evaluationPool.py", line 60, in evaluatePopulation
    results[A] = results[A].get(timeout=timeout)
  File "C:\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Win10EntVM\Downloads\gekko-stable\gekko-stable\gekkoJaponicus\promoterz\evaluationPool.py", line 30, in evaluateBackend
    P = Pool(self.poolsizes[I])
  File "C:\Python36\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Python36\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Python36\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
^C
C:\Users\Win10EntVM\Downloads\gekko-stable\gekko-stable\gekkoJaponicus>
```

**Comment by Gab0** [comment]
Cheers @anakaine 
That issue is related to multiprocessing module usage under Win64.
I do not know about this, but this may fix that, as the error says:
```
@japonicus.py
......
....
if __name__ == '__main__':
    from multiprocessing import freeze_support
    freeze_support()

    .......continues..........
```
Does `python japonicus.py -g --strat PPO` work?
I could adapt japonicus to work without multiprocessing, would be SO slow...

**Comment by anakaine** [comment]
I can see that freeze_support() is defined in spaswn.py, but cannot for the life of me find where it is being called from thats causing this error. it doesn't seem to appear in japonicus.py unless I'm blind. 

python japonicus.py -g --strat PPO does not work, throws the same error.

**Comment by Gab0** [comment]
Yeah, it does not appear at japonicus.py. I'm suggesting you to add it x}... It may fix things

**Comment by anakaine** [comment]
Adding it didn't seem to improve things, unfortunately. Then again, I'm not a python guy, so not entirely understanding what I'm doing here on in. Sorry

**Comment by Gab0** [comment]
I have never seen this error, don't mess with Win64. You can still run gekko+japonicus on a linux virtual machine, should be easy to setup. You can also share the strat with me, and I run optmizations on its settings, tell if its viable and stuff ^^.

**Comment by s5m4** [comment]
I'm just confirming this error on two independent windows 10 x64 machines (one of them running python 3.6.4). On the first machine I thought that it might have been some python installation mess-up but then on my other machine chances for that are pretty low. Interesting lines are: 

        RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()

and 

    TypeError: getresponse() got an unexpected keyword argument 'buffering'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>

but then again they might be only interesting to me because I can read them :) (I'm almost no coder)
It would be cool if this ever got solved. I run japonicus on a Ubuntu VM but I feel it's slowed down and I was hoping to run it directly on Windows to have more speed in evaluating the strategies. 

Has anyone ever found a workaround
