### ISSUE TITLE
'float' object is not subscriptable

### ISSUE THREAD

**Issue by HOllarves** [Gab0/gekkoJaponicus#45]
OS: Mac OS High Sierra
Python version: 3.6.3

the command used: `python japonicus.py -g --strat custom`

Full console response: 

```
evaluated parameters ranges:
interval                      (1, 10)
short                         (1, 16)
long                          (18, 30)
stop                          1.15
signal                        (1, 10)
thresholds.down               (-0.5, -0.1)
thresholds.up                 (0.1, 0.5)
thresholds.high               (70, 90)
thresholds.low                (15, 30)
thresholds.persistence        (1, 4)
bbparameters.optInTimePeriod  (1, 5)
bbparameters.optInNbDevUp     (1, 5)
bbparameters.optInNbDevDn     (1, 5)
bbparameters.optInMAType      (1, 5)

using candlestick dataset 2017-09-30 14:09:00 to 2017-12-31 15:07:00

	======  EPOCH 0/400  ======
Locale1
Traceback (most recent call last):
  File "japonicus.py", line 99, in <module>
    gekko_generations(TargetParameters, GenerationMethod, EvaluationMode, web=APP)
  File "/Users/hollarves/dev/gekkoJaponicus/evolution_generations.py", line 103, in gekko_generations
    World.runEPOCH()
  File "/Users/hollarves/dev/gekkoJaponicus/promoterz/sequence/parallel_world.py", line 12, in world_EPOCH
    LOCALE.run()
  File "/Users/hollarves/dev/gekkoJaponicus/promoterz/locale.py", line 51, in run
    self.loop(self.World, self)
  File "/Users/hollarves/dev/gekkoJaponicus/promoterz/sequence/standard_loop.py", line 18, in standard_loop
    locale.population)
  File "/Users/hollarves/dev/gekkoJaponicus/promoterz/validation.py", line 32, in validatePopulation
    phenotype=IndividualToSettings(population[p])
  File "/Users/hollarves/dev/gekkoJaponicus/promoterz/representation/oldschool.py", line 28, in constructPhenotype
    Value = R(individue[K], stratSettings[AttributeNames[K]])
  File "/Users/hollarves/dev/gekkoJaponicus/promoterz/representation/oldschool.py", line 23, in <lambda>
    R = lambda V, lim: ((lim[1]-lim[0])/100) * V + lim[0]
TypeError: 'float' object is not subscriptable
```
I'm not sure if this is happening because I'm using ta-lib indicators, but I don't think so. The strat works perfectly using Gekko through the terminal. The process terminates after this response. If I use -w the process continues, but I keep getting a file not found error. (some .csv file)

**Comment by HOllarves** [comment]
It was a simple typo. My bad for opening the issue.
